import { Department, Doctor, RateItem, NewsItem, Testimonial } from './types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    name: 'Breast Cancer Specialist & Surgical Oncology',
    slug: 'breast-cancer-specialist',
    iconName: 'Activity',
    shortDescription: 'Comprehensive screening, diagnosis, and surgical management of breast diseases and oncology.',
    fullDescription: 'Our Breast Oncology department offers advanced multidisciplinary care for benign and malignant breast disorders, including screening mammography, breast-conserving surgery, reconstruction, and adjuvant therapy planning.',
    facilities: ['Digital Mammography with 3D Tomosynthesis', 'Breast Ultrasound & Guided Biopsies', 'Sentinel Lymph Node Biopsy', 'Oncoplastic Breast Reconstruction'],
    headOfDepartment: 'Prof. Dr. Syeda Hasina',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Cardiology & Heart Care',
    slug: 'cardiology',
    iconName: 'HeartPulse',
    shortDescription: 'Comprehensive cardiac assessment, ECG, Echocardiography, hypertension and heart disease management.',
    fullDescription: 'Our Cardiology unit provides expert clinical evaluation, 2D Echocardiography with color Doppler, digital 12-lead ECG, hypertension control, and preventive heart care.',
    facilities: ['Digital 12-Lead ECG with Interpretation', '2D Echocardiography with Color Doppler', 'Hypertension & Lipid Clinic', 'Cardiac Emergency Care'],
    headOfDepartment: 'Dr. Salah Uddin Ahmed (Shuvro)',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Chest Medicine & Pulmonology',
    slug: 'chest-medicine',
    iconName: 'Wind',
    shortDescription: 'Expert care for asthma, COPD, tuberculosis, lung infections, and sleep-related breathing disorders.',
    fullDescription: 'Equipped with modern pulmonary function testing (PFT), bronchoscopy, and respiratory intensive care for all acute and chronic chest disorders.',
    facilities: ['Video Bronchoscopy Unit', 'Complete Pulmonary Function Lab (PFT)', 'Sleep Apnea Study (Polysomnography)', 'Allergy & Asthma Clinic'],
    headOfDepartment: 'Prof. Dr. M. A. Jalil',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Child / Paediatrics & Neonatology',
    slug: 'child-paediatrics',
    iconName: 'Baby',
    shortDescription: 'Dedicated pediatricians and neonatologists providing gentle care from newborn to adolescence.',
    fullDescription: 'Our Paediatric unit includes a state-of-the-art Level-3 NICU and PICU, general pediatric care, routine immunizations, and developmental monitoring.',
    facilities: ['Level-3 NICU & PICU with Ventilators', '24/7 Neonatal Resuscitation Team', 'Child Growth & Developmental Assessment', 'Comprehensive Immunization Center'],
    headOfDepartment: 'Prof. Dr. Tariqul Islam',
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Colorectal & Laparoscopic Surgery',
    slug: 'colorectal-surgeon',
    iconName: 'Stethoscope',
    shortDescription: 'Minimally invasive laparoscopic and laser surgeries for colon, rectum, and anal conditions.',
    fullDescription: 'Specialized in laser proctology (piles, fistula, fissure), laparoscopic colorectal resections, and complex gastrointestinal surgical interventions.',
    facilities: ['Laser Proctology Suite', 'High Definition Laparoscopic Towers', 'Anorectal Physiology Lab', 'Day Care Surgical Suite'],
    headOfDepartment: 'Prof. Dr. A. K. M. Fazlul Haque',
    imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Critical Care Medicine (ICU / CCU / HDU)',
    slug: 'critical-care-medicine',
    iconName: 'HeartPulse',
    shortDescription: '24/7 advanced multi-disciplinary intensive care for critically ill patients.',
    fullDescription: '50-bed modern ICU, CCU, and HDU setups with invasive hemodynamic monitoring, advanced mechanical ventilation, continuous renal replacement therapy (CRRT), and 1:1 nursing ratio.',
    facilities: ['State-of-the-art Servo Ventilators', 'Continuous Dialysis (CRRT) in ICU', 'Central Multi-para Monitoring System', 'Dedicated Intensivists 24/7 on Floor'],
    headOfDepartment: 'Dr. Shahabuddin Ahmed',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Dietetics & Clinical Nutrition',
    slug: 'dietician',
    iconName: 'Apple',
    shortDescription: 'Personalized medical nutrition therapy for diabetes, obesity, renal diseases, and critical care.',
    fullDescription: 'Certified clinical nutritionists formulating customized dietary management plans for in-patients and out-patients.',
    facilities: ['Body Composition Analysis', 'Diabetic & Renal Meal Planning', 'Enteral & Parenteral Nutrition Support', 'Weight Management Counseling'],
    headOfDepartment: 'Dr. Rehana Parveen',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Endocrinology, Diabetes & Thyroid',
    slug: 'endocrine-medicine',
    iconName: 'Syringe',
    shortDescription: 'Comprehensive management of diabetes mellitus, thyroid disorders, and hormonal imbalances.',
    fullDescription: 'Expert diagnostic evaluation and ongoing care for complex endocrine pathologies, gestational diabetes, thyroid nodules, and metabolic bone disorders.',
    facilities: ['Continuous Glucose Monitoring (CGM)', 'Insulin Pump Initiation & Education', 'Thyroid Ultrasound & Fine Needle Aspiration', 'Comprehensive Diabetic Foot Care'],
    headOfDepartment: 'Prof. Dr. Farooque Pathan',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'ENT, Head & Neck Surgery',
    slug: 'ent-head-neck-surgery',
    iconName: 'Ear',
    shortDescription: 'Advanced microsurgery and endoscopic sinus surgery for ear, nose, throat, and skull base diseases.',
    fullDescription: 'Offering endoscopic sinus surgery (FESS), tympanoplasty, mastoidectomy, micro-laryngeal surgery, and head & neck tumor resections.',
    facilities: ['Rigid Endoscopic Sinus Suite', 'Operating Microscopes for Micro-Ear Surgery', 'Audiometry & Tympanometry Lab', 'Voice & Swallowing Assessment'],
    headOfDepartment: 'Prof. Dr. Belal Hossain',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Eye / Ophthalmology',
    slug: 'eye-ophthalmology',
    iconName: 'Eye',
    shortDescription: 'Modern cataract micro-phaco surgery, glaucoma management, and comprehensive eye care.',
    fullDescription: 'Equipped with state-of-the-art optical coherence tomography (OCT), YAG laser, visual field analyzer, and stitchless Phaco cataract surgery.',
    facilities: ['Phacoemulsification Cataract Suite', 'Spectral Domain OCT & Fundus Camera', 'YAG & Green Laser', 'Glaucoma & Refraction Clinic'],
    headOfDepartment: 'Dr. Mahfuzur Rahman',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Gastroenterology & Hepatology',
    slug: 'gastroenterology',
    iconName: 'ShieldAlert',
    shortDescription: 'Complete diagnostic and therapeutic endoscopy, colonoscopy, and liver disease treatment.',
    fullDescription: 'Advanced endoscopy suite providing ERCP for bile duct stones, banding, polypectomy, and comprehensive chronic hepatitis care.',
    facilities: ['Video HD Upper GI Endoscopy', 'High Resolution Colonoscopy', 'ERCP for Biliary Stents & Stone Extraction', 'Fibroscan & Liver Biopsy'],
    headOfDepartment: 'Prof. Dr. Mahmud Hasan',
    imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'General & Laparoscopic Surgery',
    slug: 'general-surgeon',
    iconName: 'Scissors',
    shortDescription: 'Routine and emergency general surgery, hernia repair, gallbladder, and abdominal procedures.',
    fullDescription: 'Providing laparoscopic cholecystectomy, appendectomy, hernia repairs (TEP/TAPP), breast surgeries, and trauma care.',
    facilities: ['Modular Laminar Flow Operation Theatres', 'Laparoscopic HD 4K Systems', 'Post-Anesthesia Care Unit (PACU)', 'Emergency Trauma Team'],
    headOfDepartment: 'Prof. Dr. Shafiqul Alam',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Gynaecology & Obstetrics',
    slug: 'gynaecology',
    iconName: 'UserPlus',
    shortDescription: 'Compassionate maternal care, painless normal delivery, high-risk pregnancy, and gynecologic surgery.',
    fullDescription: 'Full continuum of women’s health services from pre-conception counseling, modern labor suites, caesarean delivery, to advanced laparoscopic hysterectomy.',
    facilities: ['Modern Labor Delivery Recovery (LDR) Rooms', 'Electronic Fetal Heart Monitoring', 'Infertility Evaluation & Laparoscopy', 'Gynecological Oncology Screening'],
    headOfDepartment: 'Prof. Dr. Rashida Begum',
    imageUrl: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Haematology & Bone Marrow Care',
    slug: 'haematologist',
    iconName: 'Droplet',
    shortDescription: 'Diagnosis and specialized treatment for anemia, leukemia, lymphoma, and bleeding disorders.',
    fullDescription: 'Dedicated clinical hematologists and transfusions specialists providing chemotherapy, clotting factor support, and blood component therapy.',
    facilities: ['Flow Cytometry & Bone Marrow Aspiration', 'Blood Component Transfusion (Platelets, FFP, PRBC)', 'Day Care Chemotherapy Infusion Center', 'Hemophilia & Thalassemia Clinic'],
    headOfDepartment: 'Dr. Aminul Islam',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Internal Medicine & Diagnostic Care',
    slug: 'medicine',
    iconName: 'Heart',
    shortDescription: 'Comprehensive inpatient and outpatient diagnostic evaluation for complex medical disorders.',
    fullDescription: 'General internal medicine experts managing multi-system disorders, infectious diseases, fever of unknown origin, hypertension, and geriatric care.',
    facilities: ['24/7 Medical Emergency Response', 'Executive Health Checkup Packages', 'Isolation Ward for Infectious Illnesses', 'Elderly Geriatric Consultation'],
    headOfDepartment: 'Prof. Dr. Md. Rafiqul Islam',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Nephrology & Kidney Dialysis',
    slug: 'nephrology-kidney-medicine',
    iconName: 'Activity',
    shortDescription: 'State-of-the-art 24/7 hemodialysis unit and treatment for acute/chronic kidney disease.',
    fullDescription: 'Modern hemodialysis stations with reverse osmosis water plant, kidney biopsies, peritoneal dialysis, and pre-transplant workup.',
    facilities: ['30-Bed Dedicated Hemodialysis Unit', 'Separate Dialysis Station for Hepatitis Patients', 'Ultrasound Guided Kidney Biopsy', 'Continuous Renal Replacement Therapy (CRRT)'],
    headOfDepartment: 'Prof. Dr. Harun Ur Rashid',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Neurology & Stroke Center',
    slug: 'neurology',
    iconName: 'Brain',
    shortDescription: 'Specialized diagnosis and therapy for stroke, epilepsy, migraines, neuropathies, and Parkinsonism.',
    fullDescription: 'Providing acute stroke thrombolysis protocol, digital EEG, EMG, nerve conduction studies (NCS), and comprehensive neuro-rehabilitation.',
    facilities: ['Digital Video EEG & EMG Lab', 'Acute Stroke Protocol with 24/7 CT/MRI', 'Nerve Conduction Studies (NCS)', 'Neuro-Rehabilitation & Physical Therapy'],
    headOfDepartment: 'Prof. Dr. Quazi Deen Mohammad',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Neurosurgery & Spine Center',
    slug: 'neuro-surgeon',
    iconName: 'Brain',
    shortDescription: 'Brain tumor microsurgery, aneurysm clipping, endoscopic skull base, and spinal fixation.',
    fullDescription: 'Equipped with neuro-navigation, operative neuro-microscopes, and intraoperative neuromonitoring for brain and spine procedures.',
    facilities: ['Carl Zeiss Neuro-Microscope Suite', 'Intraoperative C-Arm & Neuromonitoring', 'Micro-discectomy for Slip Disc', 'Emergency Brain Trauma & Hemorrhage Surgery'],
    headOfDepartment: 'Prof. Dr. Afzal Hossain',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Orthopaedic Surgery & Trauma',
    slug: 'orthopaedic-surgery',
    iconName: 'Bone',
    shortDescription: 'Joint replacement (Knee/Hip), arthroscopic ligament reconstruction, and complex fracture fixation.',
    fullDescription: 'Comprehensive orthopaedic care including total knee/hip arthroplasty, arthroscopic ACL repair, spinal deformities, and pediatric orthopaedics.',
    facilities: ['Computer-Assisted Joint Replacement', 'Arthroscopic Sports Injury Suite', 'Ilizarov & Complex Limb Reconstruction', 'Dedicated Orthopaedic Physical Therapy Unit'],
    headOfDepartment: 'Prof. Dr. M. Amjad Hossain',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Urology & Andrology Surgery',
    slug: 'urology-surgery',
    iconName: 'Activity',
    shortDescription: 'Minimally invasive laser stone removal (PCNL/RIRS), prostate surgery (TURP), and urologic oncology.',
    fullDescription: 'Equipped with Holmium laser, flexible ureteroscopes, PCNL equipment, and laparoscopic urology for kidney, bladder, and prostate treatments.',
    facilities: ['Holmium Laser Lithotripsy (RIRS/PCNL)', 'Bipolar & Laser TURP for Prostate', 'Urodynamic Study Lab', 'Male Infertility & Andrology Clinic'],
    headOfDepartment: 'Prof. Dr. Mirza Md. Fakhrul Islam',
    imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Dermatology & Venereology',
    slug: 'skin-dermatology',
    iconName: 'Sparkles',
    shortDescription: 'Clinical dermatology, eczema, psoriasis, hair loss, and cosmetic laser treatments.',
    fullDescription: 'Comprehensive clinical diagnosis of skin conditions, phototherapy, chemical peels, dermatosurgery, and laser therapy.',
    facilities: ['Narrowband UVB Phototherapy', 'CO2 Fractional Skin Laser', 'Electro-cautery & Cryosurgery', 'Patch Test Allergy Lab'],
    headOfDepartment: 'Dr. Zakir Hossain',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Plastic, Reconstructive & Burn Surgery',
    slug: 'plastic-surgery',
    iconName: 'Layers',
    shortDescription: 'Reconstructive microvascular surgery, burn management, cleft lip/palate, and cosmetic procedures.',
    fullDescription: 'Specializing in post-trauma reconstruction, microvascular flap surgery, wound care, and aesthetic surgery.',
    facilities: ['Microvascular Surgical Instrumentarium', 'Dedicated Burn Care Station', 'Cleft Lip & Palate Correction', 'Body Contouring & Scar Revision'],
    headOfDepartment: 'Prof. Dr. Rayhana Awwal',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Psychiatry & Behavioral Health',
    slug: 'psychiatrist',
    iconName: 'Smile',
    shortDescription: 'Compassionate treatment for depression, anxiety, OCD, bipolar, addiction, and psychotherapy.',
    fullDescription: 'Integrated psychiatric assessment with evidence-based pharmacotherapy and cognitive behavioral therapy (CBT).',
    facilities: ['Individual & Family Psychotherapy', 'Addiction Rehabilitation Counseling', 'Child & Adolescent Behavioral Clinic', 'Psychometric Testing Lab'],
    headOfDepartment: 'Dr. Tanvir Ahmed',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Physical Medicine & Rehabilitation',
    slug: 'physical-medicine-and-rehabilitation',
    iconName: 'Dumbbell',
    shortDescription: 'Comprehensive rehabilitation for stroke, arthritis, sports injuries, and spinal pain.',
    fullDescription: 'Specialized physiotherapy, occupational therapy, electrotherapy, and musculoskeletal ultrasound-guided injections.',
    facilities: ['Advanced Electrotherapy & Ultrasound', 'Hydrotherapy & Traction Units', 'Stroke Rehabilitation Gymnasium', 'Intra-articular PRP & Joint Injections'],
    headOfDepartment: 'Dr. Nazmul Huda',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  },
  {
    name: 'Vascular & Endovascular Surgery',
    slug: 'vascular-surgeon',
    iconName: 'Activity',
    shortDescription: 'Laser varicose vein ablation, dialysis AV fistula creation, and peripheral artery bypass.',
    fullDescription: 'Offering endovenous laser therapy (EVLT) for varicose veins, AV fistula for hemodialysis, and emergency vascular trauma repair.',
    facilities: ['Endovenous Laser Vein Ablation (EVLT)', 'AV Fistula & Graft Surgery', 'Peripheral Angiography & Stenting', 'Diabetic Foot Revascularization'],
    headOfDepartment: 'Prof. Dr. M. S. Alam',
    imageUrl: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    isActive: true,
  }
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    name: 'Dr. Md. Touhidul Islam (Rajib)',
    slug: 'dr-md-touhidul-islam-rajib',
    department: 'Internal Medicine & Diagnostic Care',
    departmentSlug: 'medicine',
    designation: 'Consultant of Medicine & Endoscopist',
    qualifications: 'MBBS (Dhaka), BCS (Health), FCPS (Medicine - Final), MD (Chest Course), PGT (Neurology), Certified Endoscopist',
    specialty: 'Medicine, Chest Diseases, Neurology, Gastro & Liver',
    roomNumber: 'Room 102, 1st Floor',
    visitingHours: '03:00 PM - 07:00 PM',
    visitingDays: ['Sunday', 'Wednesday'],
    bio: 'Experienced consultant in internal medicine, chest conditions, diagnostic endoscopy, and general healthcare at Al Insaf General Hospital, Dewanganj.',
    experienceYears: 12,
    consultationFee: 600,
    phone: '01303-359905',
    email: 'dr.touhidul@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-touhidul-islam.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Toufika Rahman',
    slug: 'dr-toufika-rahman',
    department: 'Gynaecology & Obstetrics',
    departmentSlug: 'gynaecology',
    designation: 'Consultant Gynaecologist & Surgeon',
    qualifications: 'MBBS (DU), BCS (Health), FCPS (Gynae & Obs - Final Part)',
    specialty: 'High-Risk Pregnancy, Normal Delivery, Infertility & Gynae Surgery',
    roomNumber: 'Room 105, 1st Floor',
    visitingHours: '03:00 PM - 07:00 PM',
    visitingDays: ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    bio: 'Specialist gynaecologist and obstetrician dedicated to maternal care, normal delivery, high-risk pregnancies, and women\'s health.',
    experienceYears: 10,
    consultationFee: 500,
    phone: '01913-129020',
    email: 'dr.toufika@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-toufika-rahman.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Mahbuba Rahman Munni',
    slug: 'dr-mahbuba-rahman-munni',
    department: 'Gynaecology & Obstetrics',
    departmentSlug: 'gynaecology',
    designation: 'Consultant Gynaecologist & Obstetrician Surgeon',
    qualifications: 'MBBS, BCS (Health), FCPS (Gynae & Obs - FP), DGO, MS (Gynae & Obs)',
    specialty: 'High-Risk Pregnancy, Normal Delivery, Infertility & Caesarean Gynae Surgery',
    roomNumber: 'Room 106, 1st Floor',
    visitingHours: '02:30 PM - 08:00 PM',
    visitingDays: ['Tuesday', 'Friday', 'Saturday'],
    bio: 'Specialist Gynaecologist and Obstetrician Surgeon providing maternal healthcare, painless normal deliveries, caesarean surgeries, and female reproductive care at Al Insaf General Hospital, Dewanganj.',
    experienceYears: 11,
    consultationFee: 600,
    phone: '01303-359905',
    email: 'dr.munni@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-mahbuba-rahman-munni.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Md. Shafiqul Islam',
    slug: 'dr-md-shafiqul-islam',
    department: 'General & Laparoscopic Surgery',
    departmentSlug: 'general-surgeon',
    designation: 'Assistant Professor (Surgery)',
    qualifications: 'MBBS, BCS (Health), FCPS (Surgery), MS (Surgical Oncology)',
    specialty: 'Cancer, General & Advanced Laparoscopic Surgery',
    roomNumber: 'Room 201, 2nd Floor',
    visitingHours: '02:00 PM - 07:00 PM',
    visitingDays: ['Friday'],
    bio: 'Assistant Professor and laparoscopic surgical oncologist specializing in tumor resections, laparoscopic surgery, hernia, and appendix procedures.',
    experienceYears: 15,
    consultationFee: 800,
    phone: '01715-156034',
    email: 'dr.shafiqul@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-shafiqul-islam.jpg',
    isActive: true,
  },
  {
    name: 'Dr. S.M. Alkas Tahmid',
    slug: 'dr-s-m-alkas-tahmid',
    department: 'Orthopaedic Surgery & Trauma',
    departmentSlug: 'orthopaedic-surgery',
    designation: 'Orthopaedic & Trauma Surgeon',
    qualifications: 'MBBS, BCS (Health), MS (Ortho - Final)',
    specialty: 'Bone Fracture, Joint Pain, Arthritis, Orthopaedic & Trauma Surgery',
    roomNumber: 'Room 203, 2nd Floor',
    visitingHours: '11:00 AM - 03:00 PM',
    visitingDays: ['Sunday', 'Wednesday'],
    bio: 'Specialist in orthopaedic trauma management, fracture management, joint arthritis, and bone reconstructive care.',
    experienceYears: 11,
    consultationFee: 600,
    phone: '01303-359905',
    email: 'dr.alkas@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-alkas-tahmid.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Md. Rezaul Islam',
    slug: 'dr-md-rezaul-islam',
    department: 'Child / Paediatrics & Neonatology',
    departmentSlug: 'child-paediatrics',
    designation: 'Consultant Paediatrician',
    qualifications: 'MBBS, BCS (Health), DCH (Child Health), MD (Paediatrics)',
    specialty: 'Neonatology, Child Nutrition, Adolescent & Child Health',
    roomNumber: 'Room 108, 1st Floor',
    visitingHours: '03:00 PM - 07:00 PM',
    visitingDays: ['Monday', 'Wednesday'],
    bio: 'Consultant paediatrician dedicated to newborn wellness, child infections, pediatric growth, and adolescent medicine.',
    experienceYears: 13,
    consultationFee: 500,
    phone: '01913-129020',
    email: 'dr.rezaul@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-rezaul-islam.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Salah Uddin Ahmed (Shuvro)',
    slug: 'dr-salah-uddin-ahmed-shuvro',
    department: 'Cardiology & Heart Care',
    departmentSlug: 'cardiology',
    designation: 'Clinical Cardiologist & Medicine Specialist',
    qualifications: 'MBBS, BCS (Health), D-Card (NICVD), CCD (BIRDEM)',
    specialty: 'Hypertension, Heart Diseases, ECG, Echo & Diabetes Care',
    roomNumber: 'Room 206, 2nd Floor',
    visitingHours: '10:00 AM - 07:00 PM',
    visitingDays: ['Friday', 'Saturday'],
    bio: 'Cardiologist trained at NICVD providing diagnostic cardiology, hypertension management, echocardiography, and cardiac consultation.',
    experienceYears: 14,
    consultationFee: 700,
    phone: '01715-156034',
    email: 'dr.salahuddin@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-salah-uddin.jpg',
    isActive: true,
  },
  {
    name: 'Dr. S. M. Raihan Habib',
    slug: 'dr-s-m-raihan-habib',
    department: 'Endocrinology, Diabetes & Thyroid',
    departmentSlug: 'endocrine-medicine',
    designation: 'Specialist in Diabetes, Thyroid & Endocrine Disorders',
    qualifications: 'MBBS, BCS (Health), MD (Endocrinology & Metabolism), CCD (BIRDEM)',
    specialty: 'Diabetes Mellitus, Thyroid Gland, Hormone & Metabolic Disorders',
    roomNumber: 'Room 208, 2nd Floor',
    visitingHours: '09:00 AM - 02:00 PM',
    visitingDays: ['Friday'],
    bio: 'Endocrine specialist offering advanced clinical management for diabetes mellitus, thyroid pathologies, and metabolic balance.',
    experienceYears: 12,
    consultationFee: 700,
    phone: '01303-359905',
    email: 'dr.raihan@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-raihan-habib.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Abu Sadat Md. Nazmul Islam',
    slug: 'dr-abu-sadat-md-nazmul-islam',
    department: 'Orthopaedic Surgery & Trauma',
    departmentSlug: 'orthopaedic-surgery',
    designation: 'Assistant Professor (Orthopaedics)',
    qualifications: 'MBBS, MS (Ortho)',
    specialty: 'Joint Replacement, Complex Trauma & Spine Surgery',
    roomNumber: 'Room 204, 2nd Floor',
    visitingHours: '09:00 AM - 08:00 PM',
    visitingDays: ['Friday'],
    bio: 'Assistant Professor in orthopaedics specializing in trauma reconstruction, spine problems, and complex fracture fixes.',
    experienceYears: 16,
    consultationFee: 800,
    phone: '01913-129020',
    email: 'dr.nazmul@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-nazmul-islam.jpg',
    isActive: true,
  },
  {
    name: 'Dr. Md. Mainul Islam',
    slug: 'dr-md-mainul-islam',
    department: 'Orthopaedic Surgery & Trauma',
    departmentSlug: 'orthopaedic-surgery',
    designation: 'Orthopaedic Specialist & Surgeon',
    qualifications: 'MBBS, D-Ortho (NITOR)',
    specialty: 'Trauma, Bone Setting, Arthritis & Joint Pain',
    roomNumber: 'Room 202, 2nd Floor',
    visitingHours: '03:00 PM - 09:00 PM',
    visitingDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday'],
    bio: 'NITOR-trained orthopaedic surgeon focused on conservative and operative management of trauma, arthritis, and joint pain.',
    experienceYears: 10,
    consultationFee: 600,
    phone: '01715-156034',
    email: 'dr.mainul@alinsafhospital.com',
    imageUrl: '/images/doctors/dr-mainul-islam.jpg',
    isActive: true,
  },
];

export const INITIAL_RATES: RateItem[] = [
  // Cabin & Beds
  { category: 'Cabin & Bed', code: 'CAB-VIP-01', name: 'Deluxe VIP Suite (AC, Refrigerator, Sofa, TV, Attendant Bed)', fee: 8500, unit: 'per day' },
  { category: 'Cabin & Bed', code: 'CAB-SN-02', name: 'Single AC Cabin (Private Bathroom, TV, Attendant Couch)', fee: 4500, unit: 'per day' },
  { category: 'Cabin & Bed', code: 'CAB-DB-03', name: 'Double Sharing AC Cabin (Per Bed)', fee: 2500, unit: 'per day' },
  { category: 'Cabin & Bed', code: 'CAB-GEN-04', name: 'General Ward (Male / Female with Nursing Care)', fee: 1200, unit: 'per day' },
  
  // ICU & Critical Care
  { category: 'ICU & Emergency', code: 'ICU-BED-01', name: 'ICU Bed Charge (with Dedicated Multi-Para Monitor)', fee: 7000, unit: 'per day' },
  { category: 'ICU & Emergency', code: 'ICU-VENT-02', name: 'Mechanical Ventilator Support Charge (ICU/NICU)', fee: 4000, unit: 'per day' },
  { category: 'ICU & Emergency', code: 'CCU-BED-03', name: 'Coronary Care Unit (CCU) Bed', fee: 6000, unit: 'per day' },
  { category: 'ICU & Emergency', code: 'NICU-BED-04', name: 'Neonatal ICU (NICU) Incubator Station', fee: 5000, unit: 'per day' },
  { category: 'ICU & Emergency', code: 'EMG-ADM-05', name: 'Emergency Observation (Up to 6 Hours)', fee: 1500, unit: 'per visit' },
  { category: 'ICU & Emergency', code: 'DIAL-01', name: 'Hemodialysis (Single Routine Session)', fee: 2200, unit: 'per session' },
  
  // Radiology & Imaging
  { category: 'Diagnostic & Radiology', code: 'RAD-MRI-01', name: 'MRI Brain / Spine (1.5 Tesla HD)', fee: 7500, unit: 'per scan' },
  { category: 'Diagnostic & Radiology', code: 'RAD-CT-02', name: 'CT Scan Whole Abdomen / Chest (128 Slice)', fee: 6500, unit: 'per scan' },
  { category: 'Diagnostic & Radiology', code: 'RAD-USG-03', name: 'Ultrasound Whole Abdomen (4D Color Doppler)', fee: 1800, unit: 'per test' },
  { category: 'Diagnostic & Radiology', code: 'RAD-XRY-04', name: 'Digital X-Ray Chest (P/A View)', fee: 600, unit: 'per view' },
  { category: 'Diagnostic & Radiology', code: 'RAD-MAM-05', name: 'Digital Mammography Both Breasts', fee: 3000, unit: 'per test' },
  { category: 'Diagnostic & Radiology', code: 'RAD-ECHO-06', name: '2D Echocardiography with Color Doppler', fee: 2500, unit: 'per test' },
  { category: 'Diagnostic & Radiology', code: 'RAD-ECG-07', name: '12-Lead Digital ECG with Interpretation', fee: 500, unit: 'per test' },
  
  // Pathology & Lab
  { category: 'Pathology & Lab', code: 'LAB-CBC-01', name: 'Complete Blood Count (CBC) with ESR (Automated 5-Part)', fee: 550, unit: 'per test' },
  { category: 'Pathology & Lab', code: 'LAB-LIPID-02', name: 'Lipid Profile (Total Cholesterol, HDL, LDL, Triglycerides)', fee: 1200, unit: 'per test' },
  { category: 'Pathology & Lab', code: 'LAB-LFT-03', name: 'Liver Function Test (SGPT, SGOT, Bilirubin, Alk Phos)', fee: 1400, unit: 'per test' },
  { category: 'Pathology & Lab', code: 'LAB-KFT-04', name: 'Serum Creatinine & Blood Urea Nitrogen (BUN)', fee: 600, unit: 'per test' },
  { category: 'Pathology & Lab', code: 'LAB-HBA1C-05', name: 'HbA1c (Glycated Hemoglobin HPLC Method)', fee: 900, unit: 'per test' },
  { category: 'Pathology & Lab', code: 'LAB-THY-06', name: 'Thyroid Panel (FT3, FT4, TSH by Chemiluminescence)', fee: 1600, unit: 'per test' },
  { category: 'Pathology & Lab', code: 'LAB-URINE-07', name: 'Urine Routine & Microscopic Examination (R/E)', fee: 350, unit: 'per test' },
  
  // Surgical OT
  { category: 'Surgical & OT', code: 'SURG-MAJ-01', name: 'Major Operation Theatre Charge (First 2 Hours)', fee: 8000, unit: 'per procedure' },
  { category: 'Surgical & OT', code: 'SURG-MIN-02', name: 'Minor OT / Day Surgery Charge', fee: 3500, unit: 'per procedure' },
  { category: 'Surgical & OT', code: 'SURG-LAP-03', name: 'Laparoscopic Equipment & Instrument Charge', fee: 5000, unit: 'per procedure' }
];

export const INITIAL_NEWS: NewsItem[] = [
  {
    title: '24/7 Normal Delivery & Specialized Mother-Child Wing Operational at Al Insaf General Hospital',
    slug: '24-7-normal-delivery-mother-child-wing',
    category: 'News',
    summary: 'Al Insaf General Hospital in Dewanganj operates 24/7 dedicated Normal Delivery care, specialized labor suites, and modern incubator support led by expert female gynaecologists.',
    content: 'আল-ইনসাফ জেনারেল হাসপাতাল (প্রাঃ), দেওয়ানগঞ্জ বাজার (সরকারি উচ্চ বিদ্যালয় গেট সংলগ্ন), জামালপুর-এ মা ও নবজাতকের সর্বোচ্চ চিকিৎসাসেবা নিশ্চিত করতে ২৪ ঘণ্টা নরমাল ডেলিভারি ও জরুরি গাইনি ও প্রসূতি সেবা প্রদান করা হচ্ছে। আমাদের অভিজ্ঞ কনসালট্যান্ট ও দক্ষ ধাত্রী দলের তত্ত্বাবধানে সম্পূর্ণ নিরাপদ ও জীবাণুমুক্ত পরিবেশে প্রসবকালীন সেবা প্রদান করা হয়। যোগাযোগ ও সিরিয়ালের জন্য ২৪/৭ জরুরি হটলাইন: 01303-359905, 01913-129020।',
    imageUrl: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=800',
    publishDate: '2026-09-20',
    isFeatured: true,
  },
  {
    title: 'Advanced Digital Diagnostic, 4D Color Doppler USG & Laparoscopic Surgery in Dewanganj',
    slug: 'digital-diagnostic-laparoscopic-surgery-dewanganj',
    category: 'News',
    summary: 'State-of-the-art diagnostic imaging including Digital 500mA X-Ray, 4D Color Doppler USG, automated pathology, and laparoscopic appendectomy & gallbladder surgeries now available locally.',
    content: 'দেওয়ানগঞ্জ এবং সংলগ্ন অঞ্চলের রোগীদের উন্নত চিকিৎসার জন্য আল-ইনসাফ জেনারেল হাসপাতালে যুক্ত হয়েছে অত্যাধুনিক ৪ডি কালার ডপলার আল্ট্রাসনোগ্রাফি, ডিজিটাল ৫০০ এমএ এক্স-রে, অটোমেটেড ল্যাবরেটরি এবং আধুনিক ল্যাপারোস্কপিক (ছিদ্র করে) সার্জারি ইউনিট। অভিজ্ঞ সার্জন দ্বারা পিত্তথলির পাথর, অ্যাপেন্ডিসাইটিস ও হার্নিয়া অপারেশন সফলভাবে সম্পন্ন হচ্ছে।',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    publishDate: '2026-09-10',
    isFeatured: true,
  },
  {
    title: 'Regular Free Health Screening, Diabetes & Hypertension Awareness Camp',
    slug: 'free-health-diabetes-screening-camp',
    category: 'Event',
    summary: 'Al Insaf General Hospital regularly organizes complimentary community health checkup camps providing blood glucose testing, BMI calculation, and doctor consultations.',
    content: 'সাধারণ মানুষের স্বাস্থ্য সুরক্ষায় আল-ইনসাফ জেনারেল হাসপাতাল প্রাঙ্গণে নিয়মিত ফ্রি ডায়াবেটিস ও ব্লাড প্রেসার স্ক্রিনিং ক্যাম্প অনুষ্ঠিত হয়। ক্যাম্প চলাকালীন রোগীরা বিশেষজ্ঞ চিকিৎসকদের কাছ থেকে বিনামূল্যে প্রেসক্রিপশন ও স্বাস্থ্য পরামর্শ গ্রহণ করতে পারেন।',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    publishDate: '2026-08-25',
    isFeatured: false,
  },
  {
    title: 'Notice: 24-Hour Emergency Ambulance, Oxygen Supply & Pharmacy Services',
    slug: '24-hour-emergency-ambulance-oxygen-services',
    category: 'Notice',
    summary: 'Emergency patient transport with life-support oxygen, round-the-clock emergency medical officers, and hospital pharmacy remain open 24/7.',
    content: 'জরুরি যেকোনো চিকিৎসা প্রয়োজনে আল-ইনসাফ জেনারেল হাসপাতালের ২৪ ঘণ্টা জরুরি বিভাগ, অক্সিজেন সিলিন্ডার সমৃদ্ধ অ্যাম্বুলেন্স সার্ভিস এবং সার্বক্ষণিক ফার্মেসি সেবা প্রস্তুত রয়েছে। জরুরি হটলাইন: 01303-359905, 01913-129020, 01715-156034।',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800',
    publishDate: '2026-08-01',
    isFeatured: false,
  }
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    patientName: 'Kazi Morshedul Alam',
    department: 'Orthopaedics & Joint Replacement',
    rating: 5,
    comment: 'My mother underwent total knee replacement under Prof. Dr. Amjad Hossain. The nursing staff in the post-operative ward was extraordinarily attentive and compassionate. She is now walking pain-free!',
    date: '2026-07-14',
    verified: true,
  },
  {
    patientName: 'Farhana Yasmin',
    department: 'Gynaecology & Obstetrics',
    rating: 5,
    comment: 'Exceptional care during my delivery at the Mother & Child center. Clean cabins, 24/7 doctors on duty, and prompt response from nurses whenever needed.',
    date: '2026-08-02',
    verified: true,
  },
  {
    patientName: 'Engr. Mahbubur Rahman',
    department: 'Critical Care ICU',
    rating: 5,
    comment: 'When my father was in critical condition, the ICU team led by Dr. Shahabuddin gave us hope with transparent daily briefings and world-class equipment.',
    date: '2026-08-22',
    verified: true,
  }
];

export const INITIAL_STAFF = [
  // 1. Administrative
  {
    staffId: 'AIGH-ADM-101',
    name: 'Md. Anwarul Islam',
    role: 'administrative',
    phone: '01711-223344',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    department: 'Administration & Finance',
    designation: 'Director of Administration',
    email: 'anwarul@alinsafhospital.com',
    dateOfBirth: '1978-04-12',
    bloodGroup: 'B+',
    gender: 'Male',
    address: 'House 14, Road 4, Dhanmondi, Dhaka',
    joiningDate: '2015-02-01',
    shiftTiming: 'General (09:00 AM - 05:00 PM)',
    employmentStatus: 'active',
    salary: 125000,
  },
  {
    staffId: 'AIGH-ADM-102',
    name: 'Nusrat Jahan',
    role: 'administrative',
    phone: '01819-334455',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    department: 'Human Resources',
    designation: 'HR Manager & Staff Welfare',
    email: 'hr@alinsafhospital.com',
    dateOfBirth: '1986-07-25',
    bloodGroup: 'O+',
    gender: 'Female',
    address: 'Block C, Lalmatia, Dhaka',
    joiningDate: '2018-06-15',
    shiftTiming: 'General (09:00 AM - 05:00 PM)',
    employmentStatus: 'active',
    salary: 75000,
  },
  {
    staffId: 'AIGH-ADM-103',
    name: 'Kazi Tariqul Hassan',
    role: 'administrative',
    phone: '01912-445566',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    department: 'Patient Billing & Accounts',
    designation: 'Senior Billing Officer',
    email: 'billing@alinsafhospital.com',
    dateOfBirth: '1989-11-10',
    bloodGroup: 'A+',
    gender: 'Male',
    address: 'Section 2, Mirpur, Dhaka',
    joiningDate: '2019-03-10',
    shiftTiming: 'General (09:00 AM - 05:00 PM)',
    employmentStatus: 'active',
    salary: 55000,
  },

  // 2. Doctor (connected to doctors roster)
  {
    staffId: 'AIGH-DOC-201',
    name: 'Prof. Dr. M. A. Wahab',
    role: 'doctor',
    phone: '',
    imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    department: 'Cardiology & Cardiac Surgery',
    designation: 'Professor & Chief Consultant',
    email: 'dr.wahab@alinsafhospital.com',
    dateOfBirth: '1965-03-15',
    bloodGroup: 'A+',
    gender: 'Male',
    address: 'Gulshan-2, Dhaka',
    licenseNumber: 'BMDC-A-24510',
    joiningDate: '2012-01-10',
    shiftTiming: 'Morning & Evening OPD',
    employmentStatus: 'active',
    salary: 250000,
  },
  {
    staffId: 'AIGH-DOC-202',
    name: 'Dr. Sabina Yeasmin',
    role: 'doctor',
    phone: '',
    imageUrl: 'https://images.unsplash.com/photo-1594824813571-638f026361a9?auto=format&fit=crop&q=80&w=400',
    department: 'Gynaecology & Obstetrics',
    designation: 'Associate Consultant',
    email: 'dr.sabina@alinsafhospital.com',
    dateOfBirth: '1975-09-20',
    bloodGroup: 'O+',
    gender: 'Female',
    address: 'Road 7, Dhanmondi, Dhaka',
    licenseNumber: 'BMDC-A-31290',
    joiningDate: '2016-04-15',
    shiftTiming: 'Morning & Evening OPD',
    employmentStatus: 'active',
    salary: 200000,
  },
  {
    staffId: 'AIGH-DOC-203',
    name: 'Dr. Syed Shahabuddin',
    role: 'doctor',
    phone: '',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    department: 'Critical Care / ICU',
    designation: 'Critical Care Specialist',
    email: 'dr.shahab@alinsafhospital.com',
    dateOfBirth: '1979-12-05',
    bloodGroup: 'B+',
    gender: 'Male',
    address: 'Sector 4, Uttara, Dhaka',
    licenseNumber: 'BMDC-A-38760',
    joiningDate: '2017-08-01',
    shiftTiming: 'Morning Shift & Emergency Call',
    employmentStatus: 'active',
    salary: 220000,
  },
  {
    staffId: 'AIGH-DOC-204',
    name: 'Dr. Mahbuba Rahman Munni',
    role: 'doctor',
    phone: '01303-359905',
    imageUrl: 'https://images.unsplash.com/photo-1594824813571-638f026361a9?auto=format&fit=crop&q=80&w=400',
    department: 'Gynaecology & Obstetrics',
    designation: 'Consultant Gynaecologist & Obstetrician Surgeon',
    email: 'dr.munni@alinsafhospital.com',
    dateOfBirth: '1982-10-14',
    bloodGroup: 'B+',
    gender: 'Female',
    address: 'Dewanganj Bazar, Jamalpur',
    licenseNumber: 'BMDC-A-41250',
    joiningDate: '2020-03-01',
    shiftTiming: 'OPD & On-Call Surgery',
    employmentStatus: 'active',
    salary: 220000,
  },

  // 3. Nurse
  {
    staffId: 'AIGH-NUR-301',
    name: 'Sister Mary Mondol',
    role: 'nurse',
    phone: '01715-667788',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=400',
    department: 'Nursing Administration & OT',
    designation: 'Nursing Superintendent',
    email: 'nursing@alinsafhospital.com',
    dateOfBirth: '1982-05-18',
    bloodGroup: 'AB+',
    gender: 'Female',
    address: 'Monipuri Para, Tejgaon, Dhaka',
    licenseNumber: 'BNMC-RN-12480',
    joiningDate: '2013-09-01',
    shiftTiming: 'Morning (07:00 AM - 03:00 PM)',
    employmentStatus: 'active',
    salary: 60000,
  },
  {
    staffId: 'AIGH-NUR-302',
    name: 'Ruma Akter',
    role: 'nurse',
    phone: '01918-778899',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    department: 'Intensive Care Unit (ICU)',
    designation: 'Senior Staff Nurse (ICU)',
    email: 'ruma.nurse@alinsafhospital.com',
    dateOfBirth: '1990-08-14',
    bloodGroup: 'B+',
    gender: 'Female',
    address: 'Rayerbazar, Dhaka',
    licenseNumber: 'BNMC-RN-28490',
    joiningDate: '2018-11-20',
    shiftTiming: 'Rotational (Morning/Evening/Night)',
    employmentStatus: 'active',
    salary: 42000,
  },
  {
    staffId: 'AIGH-NUR-303',
    name: 'Shima Begum',
    role: 'nurse',
    phone: '01822-889900',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=400',
    department: 'General Inpatient Cabins',
    designation: 'Staff Nurse',
    email: 'shima.nurse@alinsafhospital.com',
    dateOfBirth: '1992-02-28',
    bloodGroup: 'O+',
    gender: 'Female',
    address: 'Salimullah Road, Mohammadpur, Dhaka',
    licenseNumber: 'BNMC-RN-35120',
    joiningDate: '2020-02-15',
    shiftTiming: 'Evening (03:00 PM - 11:00 PM)',
    employmentStatus: 'active',
    salary: 38000,
  },

  // 4. Pharmacist
  {
    staffId: 'AIGH-PHM-401',
    name: 'Md. Rafiqul Alam',
    role: 'pharmacist',
    phone: '01716-112233',
    imageUrl: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&q=80&w=400',
    department: 'Central Hospital Pharmacy',
    designation: 'Head of Pharmacy',
    email: 'pharmacy@alinsafhospital.com',
    dateOfBirth: '1984-06-11',
    bloodGroup: 'A+',
    gender: 'Male',
    address: 'Green Road, Dhaka',
    licenseNumber: 'PCB-REG-5432',
    joiningDate: '2014-07-01',
    shiftTiming: 'General (09:00 AM - 05:00 PM)',
    employmentStatus: 'active',
    salary: 65000,
  },
  {
    staffId: 'AIGH-PHM-402',
    name: 'Tanzina Sultana',
    role: 'pharmacist',
    phone: '01833-223344',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=400',
    department: 'Outdoor Pharmacy & Dispensary',
    designation: 'Clinical Dispenser',
    email: 'tanzina.pharm@alinsafhospital.com',
    dateOfBirth: '1993-10-19',
    bloodGroup: 'O+',
    gender: 'Female',
    address: 'Ring Road, Shyamoli, Dhaka',
    licenseNumber: 'PCB-REG-8921',
    joiningDate: '2021-04-10',
    shiftTiming: 'Morning (08:00 AM - 04:00 PM)',
    employmentStatus: 'active',
    salary: 42000,
  },

  // 5. Receptionist
  {
    staffId: 'AIGH-RCP-501',
    name: 'Farhana Hossain',
    role: 'receptionist',
    phone: '01717-334455',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    department: 'Front Desk & Patient Admission',
    designation: 'Senior Front Desk Executive',
    email: 'reception@alinsafhospital.com',
    dateOfBirth: '1994-01-22',
    bloodGroup: 'B+',
    gender: 'Female',
    address: 'Jigatola, Dhanmondi, Dhaka',
    joiningDate: '2019-08-01',
    shiftTiming: 'Morning (07:30 AM - 03:30 PM)',
    employmentStatus: 'active',
    salary: 32000,
  },
  {
    staffId: 'AIGH-RCP-502',
    name: 'Arifur Rahman',
    role: 'receptionist',
    phone: '01919-445566',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    department: 'Emergency Reception & Triage',
    designation: 'Emergency Receptionist',
    email: 'emergency.rec@alinsafhospital.com',
    dateOfBirth: '1996-04-09',
    bloodGroup: 'A+',
    gender: 'Male',
    address: 'Hazaribagh, Dhaka',
    joiningDate: '2022-01-15',
    shiftTiming: 'Night (11:00 PM - 07:30 AM)',
    employmentStatus: 'active',
    salary: 30000,
  },

  // 6. Security
  {
    staffId: 'AIGH-SEC-601',
    name: 'M. Azizul Haque',
    role: 'security',
    phone: '01718-556677',
    imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    department: 'Security & Surveillance',
    designation: 'Chief Security Officer',
    email: 'security@alinsafhospital.com',
    dateOfBirth: '1970-11-15',
    bloodGroup: 'O+',
    gender: 'Male',
    address: 'Staff Quarters, Dhanmondi, Dhaka',
    joiningDate: '2015-05-10',
    shiftTiming: 'Day (08:00 AM - 06:00 PM)',
    employmentStatus: 'active',
    salary: 45000,
  },
  {
    staffId: 'AIGH-SEC-602',
    name: 'Md. Kamrul Islam',
    role: 'security',
    phone: '01812-667788',
    imageUrl: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=400',
    department: 'Emergency & Ambulance Entrance',
    designation: 'Senior Security Guard',
    email: '',
    dateOfBirth: '1988-03-30',
    bloodGroup: 'B+',
    gender: 'Male',
    address: 'Kamrangirchar, Dhaka',
    joiningDate: '2019-10-01',
    shiftTiming: 'Rotational 8-Hours',
    employmentStatus: 'active',
    salary: 22000,
  },

  // 7. Ward Boy
  {
    staffId: 'AIGH-WRD-701',
    name: 'Md. Belal Hossain',
    role: 'wardboy',
    phone: '01719-778899',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400',
    department: 'Surgical & Inpatient Ward',
    designation: 'Senior Ward Attendant',
    email: '',
    dateOfBirth: '1987-08-12',
    bloodGroup: 'AB+',
    gender: 'Male',
    address: 'Lalbagh, Dhaka',
    joiningDate: '2016-03-01',
    shiftTiming: 'Morning (07:00 AM - 03:00 PM)',
    employmentStatus: 'active',
    salary: 24000,
  },
  {
    staffId: 'AIGH-WRD-702',
    name: 'Jahangir Alam',
    role: 'wardboy',
    phone: '01915-889900',
    imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
    department: 'Operation Theatre & Transport',
    designation: 'OT Ward Boy',
    email: '',
    dateOfBirth: '1995-12-04',
    bloodGroup: 'O+',
    gender: 'Male',
    address: 'Armanitola, Old Dhaka',
    joiningDate: '2021-07-15',
    shiftTiming: 'Rotational Shifts',
    employmentStatus: 'active',
    salary: 20000,
  },

  // 8. Technician
  {
    staffId: 'AIGH-TEC-801',
    name: 'Engr. Saiful Islam',
    role: 'technician',
    phone: '01720-990011',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    department: 'Radiology & Imaging',
    designation: 'Senior CT & MRI Technologist',
    email: 'radiology.tech@alinsafhospital.com',
    dateOfBirth: '1985-02-17',
    bloodGroup: 'A+',
    gender: 'Male',
    address: 'Kolabagan, Dhaka',
    licenseNumber: 'BME-TEC-7104',
    joiningDate: '2014-10-12',
    shiftTiming: 'Morning (08:00 AM - 04:00 PM)',
    employmentStatus: 'active',
    salary: 58000,
  },
  {
    staffId: 'AIGH-TEC-802',
    name: 'Mahmuda Khatun',
    role: 'technician',
    phone: '01824-001122',
    imageUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=400',
    department: 'Pathology & Biochemistry Lab',
    designation: 'Medical Lab Technologist',
    email: 'lab.tech@alinsafhospital.com',
    dateOfBirth: '1991-09-08',
    bloodGroup: 'B+',
    gender: 'Female',
    address: 'Azimpur, Dhaka',
    licenseNumber: 'SMF-LAB-9042',
    joiningDate: '2018-05-20',
    shiftTiming: 'Evening (02:00 PM - 10:00 PM)',
    employmentStatus: 'active',
    salary: 45000,
  },

  // 9. Cleaner
  {
    staffId: 'AIGH-CLN-901',
    name: 'Md. Monirul Islam',
    role: 'cleaner',
    phone: '01721-112233',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    department: 'Housekeeping & Infection Control',
    designation: 'Sanitation Supervisor',
    email: '',
    dateOfBirth: '1983-04-20',
    bloodGroup: 'B+',
    gender: 'Male',
    address: 'Hazaribagh, Dhaka',
    joiningDate: '2015-08-01',
    shiftTiming: 'Morning (06:00 AM - 02:00 PM)',
    employmentStatus: 'active',
    salary: 25000,
  },
  {
    staffId: 'AIGH-CLN-902',
    name: 'Amena Begum',
    role: 'cleaner',
    phone: '01825-223344',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    department: 'Ward & Cabin Hygiene',
    designation: 'Ward Cleaner',
    email: '',
    dateOfBirth: '1989-11-03',
    bloodGroup: 'A+',
    gender: 'Female',
    address: 'Kamrangirchar, Dhaka',
    joiningDate: '2018-09-10',
    shiftTiming: 'Morning (07:00 AM - 03:00 PM)',
    employmentStatus: 'active',
    salary: 18000,
  },
];

